blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/gusevm1/darcy-hackathon/discussions
    about: Use Discussions for questions instead of issues
